# Generated by Django 5.1.4 on 2025-01-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzinara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
