# Generated by Django 5.1.4 on 2025-01-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzinara', '0002_alter_contact_info_date_alter_contact_info_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
