# Generated by Django 5.1.4 on 2025-01-02 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzinara', '0003_contact_info_facebook_contact_info_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
