# Generated by Django 5.1.4 on 2025-01-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzinara', '0006_business_appointmentpagetheme_operatinghours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='website',
        ),
        migrations.AddField(
            model_name='business',
            name='type_of_business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
