# Generated by Django 5.1.4 on 2025-01-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzinara', '0007_remove_business_website_business_type_of_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatinghours',
            old_name='is_closed',
            new_name='operates_public_holidays',
        ),
        migrations.RenameField(
            model_name='operatinghours',
            old_name='closing_time',
            new_name='weekday_closing_time',
        ),
        migrations.RenameField(
            model_name='operatinghours',
            old_name='opening_time',
            new_name='weekday_opening_time',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='day',
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='operates_weekends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='public_holiday_closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='public_holiday_opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='saturday_closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='saturday_opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='sunday_closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='sunday_opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
