# Generated by Django 5.1.4 on 2025-01-04 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzinara', '0009_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='Appzinara.business'),
        ),
        migrations.AlterField(
            model_name='service',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Appzinara.business'),
        ),
        migrations.DeleteModel(
            name='AppointmentPageTheme',
        ),
    ]
