# Generated by Django 5.1.4 on 2025-01-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzinara', '0011_business_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Appzinara.business'),
        ),
    ]
