# Generated by Django 5.1.4 on 2025-01-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzinara', '0012_alter_service_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
